import enum
from enum import Enum


class BlacklistTypeEnum(str, enum.Enum):
    USER_ID = "USER_ID"
    CUSTOMER_ID = "CUSTOMER_ID"
    ACCOUNT_NUMBER = "ACCOUNT_NUMBER"
    DEVICE_ID = "DEVICE_ID"
    TERMINAL_ID = "TERMINAL_ID"
    IP_ADDRESS = "IP_ADDRESS"
    MERCHANT_ID = "MERCHANT_ID"
    INVOICE_NUMBER = "INVOICE_NUMBER"
    RRN = "RRN"
    PAYMENT_CODE = "PAYMENT_CODE"
    BILLER_ID = "BILLER_ID"
    CUSTOMER_PHONE = "CUSTOMER_PHONE"
    CUSTOMER_EMAIL = "CUSTOMER_EMAIL"
    VIRTUAL_ACCOUNT_NUMBER = "VIRTUAL_ACCOUNT_NUMBER"


class TransactionStatusEnum(str, enum.Enum):
    FLAGGED = "FLAGGED"
    PENDING = "PENDING"  # Legacy DB value; normalized to FLAGGED in API responses.
    UNDER_REVIEW = "UNDER_REVIEW"
    SAFE = "SAFE"
    FRAUD = "FRAUD"


class RuleOperatorEnum(str, enum.Enum):
    EQ = "="
    NEQ = "!="
    GT = ">"
    LT = "<"
    GTE = ">="
    LTE = "<="


class ServiceScopeEnum(str, enum.Enum):
    ALL = "ALL"
    AGENUSA = "AGENUSA"
    NUSABILL = "NUSABILL"


class RuleActionEnum(str, enum.Enum):
    BLOCK = "BLOCK"
    REVIEW = "REVIEW"
    FLAG = "FLAG"


class RuleSeverityEnum(str, enum.Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


# ==========================================
# RISK LEVEL ENUM (Tambahan Baru)
# ==========================================
class RiskLevelEnum(str, enum.Enum):
    SAFE = "SAFE"
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class PatternSourceEnum(str, enum.Enum):
    """Indicates where a pattern originated from"""
    MANUAL_CREATE = "MANUAL_CREATE"      # Manually created by user
    MANUAL_REVIEW = "MANUAL_REVIEW"      # Generated from manual fraud reviews
    RETRAIN_ML = "RETRAIN_ML"            # Generated from ML retrain process


class ReviewDecisionEnum(str, enum.Enum):
    SAFE = "SAFE"
    FRAUD = "FRAUD"


class AlertStatusEnum(str, enum.Enum):
    OPEN = "OPEN"
    IN_PROGRESS = "IN_PROGRESS"
    RESOLVED = "RESOLVED"
    REOPENED = "REOPENED"
    OVERRIDDEN = "OVERRIDDEN"


class ActivityActionEnum(str, enum.Enum):
    # Auth & Sessions
    LOGIN = "LOGIN"
    LOGIN_FAILED = "LOGIN_FAILED"
    LOGOUT = "LOGOUT"
    SESSION_REVOKED = "SESSION_REVOKED"
    TOKEN_REFRESHED = "TOKEN_REFRESHED" 

    # Accounts 
    ACCOUNT_CREATED = "ACCOUNT_CREATED"
    ACCOUNT_SUSPENDED = "ACCOUNT_SUSPENDED"
    ACCOUNT_ROLE_CHANGED = "ACCOUNT_ROLE_CHANGED"
    ACCOUNT_LOCKED = "ACCOUNT_LOCKED"
    ACCOUNT_ACTIVATED = "ACCOUNT_ACTIVATED"
    ACCOUNT_UPDATED = "ACCOUNT_UPDATED"
    PASSWORD_CHANGED = "PASSWORD_CHANGED"
    PASSWORD_RESET = "PASSWORD_RESET"

    # Rules Engine
    RULE_CREATED = "RULE_CREATED"
    RULE_UPDATED = "RULE_UPDATED"
    RULE_DELETED = "RULE_DELETED" 
    RULE_TRIGGERED = "RULE_TRIGGERED" 

    # Patterns (ML & Manual)
    PATTERN_CREATED = "PATTERN_CREATED"
    PATTERN_UPDATED = "PATTERN_UPDATED"
    PATTERN_AUTO_DISABLE = "PATTERN_AUTO_DISABLE"
    PATTERN_AUTO_PROMOTE = "PATTERN_AUTO_PROMOTE"
    PATTERN_ACTIVATED = "PATTERN_ACTIVATED"
    PATTERN_DEACTIVATED = "PATTERN_DEACTIVATED"
    PATTERN_REACTIVATED = "PATTERN_REACTIVATED" 
    PATTERN_TRIGGERED = "PATTERN_TRIGGERED" 

    # Blacklist 
    BLACKLIST_ADD = "BLACKLIST_ADD"
    BLACKLIST_REMOVE = "BLACKLIST_REMOVE"
    BLACKLIST_HIT = "BLACKLIST_HIT"
    BLACKLIST_CREATED = "BLACKLIST_CREATED"
    BLACKLIST_UPDATED = "BLACKLIST_UPDATED"
    BLACKLIST_DELETED = "BLACKLIST_DELETED"
    BLACKLIST_APPROVED = "BLACKLIST_APPROVED"
    BLACKLIST_REJECTED = "BLACKLIST_REJECTED"
    BLACKLIST_ACTIVATED = "BLACKLIST_ACTIVATED"
    BLACKLIST_DEACTIVATED = "BLACKLIST_DEACTIVATED"
    BLACKLIST_BULK_IMPORT = "BLACKLIST_BULK_IMPORT"

    # Alerts & Reviews
    FLAG_TRANSACTION = "FLAG_TRANSACTION"
    ALERT_CREATED = "ALERT_CREATED"   
    ALERT_CLAIMED = "ALERT_CLAIMED"   
    ALERT_RELEASED = "ALERT_RELEASED"
    ALERT_UPDATED = "ALERT_UPDATED"
    REVIEW_APPROVED = "REVIEW_APPROVED"
    REVIEW_REJECTED = "REVIEW_REJECTED"
    REVIEW_OVERRIDDEN = "REVIEW_OVERRIDDEN"
    SOFT_DELETE_REVIEW = "SOFT_DELETE_REVIEW"
    REPORT_FALSE_NEGATIVE = "REPORT_FALSE_NEGATIVE"

    # Reports
    REPORT_GENERATED = "REPORT_GENERATED"
    REPORT_DOWNLOADED = "REPORT_DOWNLOADED"
    REPORT_DELETED = "REPORT_DELETED"

    # ML Engine
    ML_SCORING_COMPLETED = "ML_SCORING_COMPLETED"


class SeverityLevelEnum(str, enum.Enum):
    INFO = "INFO"
    WARNING = "WARNING"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class EventSourceEnum(str, enum.Enum):
    AUTH = "AUTH"
    RULE_ENGINE = "RULE_ENGINE"
    PATTERN_ENGINE = "PATTERN_ENGINE"
    MANUAL_REVIEW = "MANUAL_REVIEW"
    BLACKLIST = "BLACKLIST"
    ML = "ML"
    SYSTEM = "SYSTEM"
    REPORTS = "REPORTS"


class TimelineTypeEnum(str, enum.Enum):
    TIMELINE_FRAUD = "TIMELINE_FRAUD"
    TIMELINE_ALERT = "TIMELINE_ALERT"
    TIMELINE_REVIEW = "TIMELINE_REVIEW"
    TIMELINE_SYSTEM = "TIMELINE_SYSTEM"
    TIMELINE_SECURITY = "TIMELINE_SECURITY"


class ReportTypeEnum(str, Enum):
    FRAUD_DETECTION = "FRAUD_DETECTION"
    FRAUD_PATTERN   = "FRAUD_PATTERN"
    TRANSACTION = "TRANSACTION"
    MANUAL_REVIEW = "MANUAL_REVIEW"
    ALERT = "ALERT"
    BLACKLIST = "BLACKLIST"
    ACTIVITY_LOG = "ACTIVITY_LOG"
    ML_PERFORMANCE = "ML_PERFORMANCE"


class ReportFormatEnum(str, Enum):
    PDF = "PDF"
    XLSX = "XLSX"
    CSV = "CSV"


class ReportStatusEnum(str, Enum):
    PENDING = "PENDING"
    PROCESSING = "PROCESSING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
