import React from 'react';

const ReportPreview = ({ report, onDownload }) => {
  if (!report) {
    return (
      <div className="preview-empty-state">
        <i className="bi bi-file-earmark-text" style={{ fontSize: '4rem', color: '#d4d4d4' }}></i>
        <h4 className="mt-3">No Report Selected</h4>
        <p className="text-muted">Select a report from the list to view details</p>
      </div>
    );
  }

  const formatDate = (dateString) => {
    const date = new Date(dateString);
    return new Intl.DateTimeFormat('id-ID', {
      dateStyle: 'full',
      timeStyle: 'long'
    }).format(date);
  };

  // Generate preview content based on report type
  const generatePreviewContent = () => {
    const baseContent = {
      'Monthly Summary': {
        sections: [
          { title: 'Executive Summary', items: ['Total Transactions: 4,523', 'Fraud Rate: 8.5%', 'Total Amount: Rp 2.5M'] },
          { title: 'Transaction Breakdown', items: ['Legit: 4,138 (91.5%)', 'Fraud: 385 (8.5%)', 'Pending Review: 0'] },
          { title: 'Top Locations', items: ['Jakarta: 1,250 transactions', 'Surabaya: 890 transactions', 'Bandung: 720 transactions'] }
        ]
      },
      'Fraud Analysis': {
        sections: [
          { title: 'Fraud Overview', items: ['Total Fraud Cases: 385', 'Average Fraud Amount: Rp 1.2M', 'Fraud Trend: ↑ 12%'] },
          { title: 'Fraud Patterns', items: ['High-risk hours: 22:00 - 02:00', 'Top fraud locations: Jakarta, Medan', 'Common fraud types: Card cloning, Identity theft'] },
          { title: 'Recommendations', items: ['Increase monitoring at night', 'Enhanced verification for high-value transactions', 'Location-based risk scoring'] }
        ]
      },
      'Transaction Report': {
        sections: [
          { title: 'Transaction Summary', items: ['Total Volume: 4,523', 'Total Value: Rp 2.5B', 'Avg Transaction: Rp 552K'] },
          { title: 'Time Distribution', items: ['Peak Hours: 12:00 - 14:00', 'Lowest Activity: 03:00 - 05:00', 'Weekend vs Weekday: 35% vs 65%'] },
          { title: 'Payment Methods', items: ['Credit Card: 45%', 'Debit Card: 35%', 'E-Wallet: 20%'] }
        ]
      },
      'Location Analysis': {
        sections: [
          { title: 'Regional Distribution', items: ['Java: 68%', 'Sumatra: 18%', 'Other Islands: 14%'] },
          { title: 'City Rankings', items: ['Jakarta: 1,250 (27.6%)', 'Surabaya: 890 (19.7%)', 'Bandung: 720 (15.9%)'] },
          { title: 'Risk Assessment', items: ['High Risk: Jakarta, Medan', 'Medium Risk: Surabaya, Palembang', 'Low Risk: Bandung, Semarang'] }
        ]
      },
      'Custom Report': {
        sections: [
          { title: 'Custom Metrics', items: ['User-defined filters applied', 'Custom date range: Selected period', 'Specific status: As configured'] },
          { title: 'Data Summary', items: ['Records analyzed: Varies', 'Data points: Multiple dimensions', 'Output format: As selected'] },
          { title: 'Export Details', items: ['Charts included: Yes/No', 'Details level: Full/Summary', 'File format: PDF/Excel/CSV'] }
        ]
      }
    };

    return baseContent[report.type] || baseContent['Custom Report'];
  };

  const previewContent = generatePreviewContent();

  return (
    <div className="report-preview-content">
      {/* Preview Header */}
      <div className="preview-header">
        <div className="preview-title-section">
          <h3 className="preview-title">{report.type}</h3>
          <p className="preview-meta">
            <span className="badge bg-secondary me-2">{report.format}</span>
            <span className="text-muted">Report ID: {report.id}</span>
          </p>
        </div>
        {report.status === 'Completed' && (
          <button className="btn btn-danger" onClick={onDownload}>
            <i className="bi bi-download me-2"></i>
            Download {report.format}
          </button>
        )}
      </div>

      {/* Report Info */}
      <div className="report-info-section">
        <div className="row">
          <div className="col-md-6">
            <div className="info-item">
              <i className="bi bi-calendar3"></i>
              <div>
                <div className="info-label">Generated Date</div>
                <div className="info-value">{formatDate(report.generatedDate)}</div>
              </div>
            </div>
          </div>
          <div className="col-md-6">
            <div className="info-item">
              <i className="bi bi-person-circle"></i>
              <div>
                <div className="info-label">Generated By</div>
                <div className="info-value">{report.generatedBy}</div>
              </div>
            </div>
          </div>
          <div className="col-md-6">
            <div className="info-item">
              <i className="bi bi-file-earmark"></i>
              <div>
                <div className="info-label">File Size</div>
                <div className="info-value">{report.size}</div>
              </div>
            </div>
          </div>
          <div className="col-md-6">
            <div className="info-item">
              <i className="bi bi-check-circle"></i>
              <div>
                <div className="info-label">Status</div>
                <div className="info-value">
                  <span className={`badge ${
                    report.status === 'Completed' ? 'bg-success' : 
                    report.status === 'Processing' ? 'bg-warning' : 'bg-danger'
                  }`}>
                    {report.status}
                  </span>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Preview Content */}
      {report.status === 'Completed' && (
        <div className="preview-document">
          <div className="document-header">
            <h4>
              <i className="bi bi-file-text me-2"></i>
              Report Preview
            </h4>
            <p className="text-muted">This is a simplified preview. Download for full details.</p>
          </div>
          
          <div className="document-body">
            {previewContent.sections.map((section, index) => (
              <div key={index} className="preview-section">
                <h5 className="section-title">{section.title}</h5>
                <ul className="section-content">
                  {section.items.map((item, itemIndex) => (
                    <li key={itemIndex}>{item}</li>
                  ))}
                </ul>
              </div>
            ))}
          </div>

          <div className="document-footer">
            <div className="alert alert-info mb-0">
              <i className="bi bi-info-circle me-2"></i>
              This is a preview only. The actual {report.format} file contains detailed charts, tables, and comprehensive analysis.
            </div>
          </div>
        </div>
      )}

      {report.status === 'Processing' && (
        <div className="processing-state">
          <div className="spinner-border text-warning" role="status">
            <span className="visually-hidden">Processing...</span>
          </div>
          <h5 className="mt-3">Generating Report...</h5>
          <p className="text-muted">Please wait while we prepare your {report.type}</p>
        </div>
      )}

      {report.status === 'Failed' && (
        <div className="failed-state">
          <i className="bi bi-exclamation-triangle text-danger" style={{ fontSize: '3rem' }}></i>
          <h5 className="mt-3 text-danger">Report Generation Failed</h5>
          <p className="text-muted">There was an error generating this report. Please try again.</p>
          <button className="btn btn-outline-danger mt-2">
            <i className="bi bi-arrow-clockwise me-2"></i>
            Retry
          </button>
        </div>
      )}
    </div>
  );
};

export default ReportPreview;